#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""
Train a small-sample, interpretable event-level classifier from the outputs of
four_detector_event_analysis_with_event_decision.py.

The four SCADA detectors remain the feature extractor. This script learns how
to combine short-stop, cluster, persistent, confirmed-localized and rejected-
localized evidence into an event-level normal/anomaly probability.

Recommended project layout
--------------------------
wind_farm_fault_detection/
├─ scripts/
│  ├─ four_detector_event_analysis_power_confirmed.py
│  ├─ four_detector_event_analysis_with_event_decision.py
│  └─ train_event_level_ml.py                 <- this file
└─ outputs/
   ├─ farmC_four_detector_event_level/
   │  └─ farm_C/
   │     ├─ all_events_event_level_features.csv
   │     ├─ all_events_detected_segments_raw.csv
   │     ├─ all_events_detected_segments.csv
   │     └─ all_events_event_level_decisions.csv   (optional baseline)
   └─ event_level_ml/                       <- generated by this script

Main outputs
------------
ml_model_comparison.csv
ml_outer_fold_metrics.csv
ml_repeated_cv_predictions.csv
ml_event_predictions.csv
ml_selected_model_metrics.json
ml_selected_model_confusion_matrix.csv
ml_feature_importance.csv
ml_event_explanations.csv
ml_time_holdout_predictions.csv
ml_time_holdout_metrics.json
final_model_training_predictions.csv
event_level_model.joblib
training_manifest.json

Example
-------
python .\\wind_farm_fault_detection\\scripts\\train_event_level_ml.py `
  --input-dir ".\\wind_farm_fault_detection\\outputs\\farmC_four_detector_event_level\\farm_C" `
  --output-dir ".\\wind_farm_fault_detection\\outputs\\event_level_ml" `
  --cv-splits 5 `
  --cv-repeats 10 `
  --inner-splits 4 `
  --max-normal-fpr 0.25

Notes
-----
1. metadata_label is the target and is never used as a predictor.
2. Previous rule decisions and event descriptions are excluded to prevent
   leakage.
3. Raw event duration is excluded as a direct predictor. It is used only to
   construct rates and coverage fractions.
4. Hyperparameters and the probability threshold are selected inside the
   training portion of each outer fold.
5. Logistic Regression is preferred when its balanced accuracy is within the
   configured tolerance of the best model, because it is more interpretable.
"""

from __future__ import annotations

import argparse
import json
import math
import sys
import warnings
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Iterable, Optional

import joblib
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from sklearn.base import BaseEstimator, clone
from sklearn.ensemble import RandomForestClassifier
from sklearn.impute import SimpleImputer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import (
    accuracy_score,
    balanced_accuracy_score,
    confusion_matrix,
    f1_score,
    precision_score,
    recall_score,
    roc_auc_score,
)
from sklearn.model_selection import (
    GridSearchCV,
    RepeatedStratifiedKFold,
    StratifiedKFold,
    cross_val_predict,
)
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import RobustScaler
from sklearn.tree import DecisionTreeClassifier


# =============================================================================
# 1. CONSTANTS AND CONFIGURATION
# =============================================================================

TARGET_MAP = {"normal": 0, "anomaly": 1}
LABEL_MAP = {0: "normal", 1: "anomaly"}

# Explicitly removed because they leak the label, copy the previous rule system,
# encode identity/time, or are text fields unsuitable for the numeric model.
LEAKAGE_OR_ID_COLUMNS = {
    "farm_id",
    "event_id",
    "metadata_label",
    "metadata_start",
    "metadata_end",
    "event_description",
    "analysis_data_start",
    "analysis_data_end",
    "detector_families",
    "binary_decision",
    "detailed_status",
    "decision_level",
    "automatic_anomaly",
    "manual_review",
    "strong_evidence_paths",
    "decision_reason",
    "metadata_match",
    # Raw event duration can accidentally encode metadata construction policy.
    # It remains available internally for rates/coverage but is not a predictor.
    "event_duration_minutes",
    "event_duration_hours",
    "event_duration_days",
    "sampling_minutes",
    "sampling_minutes_used_for_censoring",
}

TRUE_TEXT = {"true", "1", "yes", "y", "t"}

# Curated, domain-grounded predictors. Keeping the feature set compact is
# important because Farm C currently has only about 58 labelled events.
MODEL_FEATURE_COLUMNS = [
    # Repeated short-stop evidence
    "short_episode_count", "short_rate_per_day",
    "direct_recovery_short_episode_count",
    "variability_only_short_episode_count",
    "max_short_count_2h", "max_short_count_24h",
    "weak_cluster_count", "strong_cluster_count",
    "maximum_episodes_in_strong_cluster",
    "direct_recovery_short_ratio", "variability_only_short_ratio",
    "raw_short_detector_score_max", "raw_short_abnormal_fraction_max",
    "raw_short_power_dip_score_max", "raw_short_power_recovery_score_max",
    "raw_short_power_variability_score_max",
    "raw_short_direct_recovery_fraction",
    "raw_short_variability_support_fraction",

    # Persistent system-state evidence
    "persistent_segment_count", "persistent_merged_interval_count",
    "max_persistent_hours", "total_persistent_hours",
    "persistent_coverage_fraction",
    "raw_persistent_detector_score_max",
    "raw_persistent_abnormal_fraction_max",
    "persistent_active_at_event_end",
    "log1p_max_persistent_hours", "log1p_total_persistent_hours",

    # Power-confirmed localized evidence
    "confirmed_localized_segment_count",
    "confirmed_localized_merged_interval_count",
    "max_confirmed_localized_hours",
    "total_confirmed_localized_hours",
    "confirmed_localized_coverage_fraction",
    "confirmed_localized_detector_score_max",
    "confirmed_localized_abnormal_fraction_max",
    "confirmed_localized_dominant_signal_count_max",
    "confirmed_localized_max_active_signal_count_max",
    "confirmed_localized_max_stable_signal_count_max",
    "confirmed_localized_mean_sensor_set_overlap_mean",
    "confirmed_localized_long_power_dip_signal_count_max",
    "confirmed_localized_long_power_recovery_signal_count_max",
    "confirmed_localized_long_power_recovery_ratio_mean",
    "log1p_max_confirmed_localized_hours",
    "log1p_total_confirmed_localized_hours",

    # Sensor-state candidates rejected only by power-boundary confirmation
    "rejected_localized_candidate_count",
    "max_rejected_localized_hours", "total_rejected_localized_hours",
    "rejected_localized_coverage_fraction",
    "rejected_localized_detector_score_max",
    "rejected_localized_abnormal_fraction_max",
    "rejected_localized_dominant_signal_count_max",
    "rejected_localized_max_active_signal_count_max",
    "rejected_localized_max_stable_signal_count_max",
    "rejected_localized_mean_sensor_set_overlap_mean",
    "rejected_localized_long_power_dip_signal_count_max",
    "rejected_localized_long_power_recovery_signal_count_max",
    "rejected_localized_long_power_drop_ratio_max",
    "rejected_localized_long_power_recovery_ratio_max",
    "rejected_missing_start_count", "rejected_missing_end_count",
    "rejected_missing_both_count",
    "rejected_start_dip_fraction", "rejected_end_recovery_fraction",
    "raw_localized_reaches_event_end",
    "log1p_max_rejected_localized_hours",
    "log1p_total_rejected_localized_hours",

    # Combined and multi-detector evidence
    "confirmed_anomaly_coverage_fraction", "detector_family_count",
    "right_censored",
    "timeline_max_detector_count",
    "timeline_multi_detector_coverage_fraction",
    "timeline_mean_smoothed_score_max",
    "timeline_mean_abnormal_fraction_max",
    "timeline_mean_persistent_system_fraction_max",
    "timeline_mean_localized_active_fraction_max",
    "timeline_mean_localized_stable_signal_count_max",
    "timeline_mean_localized_sensor_set_overlap_max",
]


@dataclass(frozen=True)
class ThresholdResult:
    threshold: float
    score: float
    balanced_accuracy: float
    f1: float
    recall: float
    specificity: float
    normal_false_positive_rate: float


@dataclass(frozen=True)
class ModelSpec:
    name: str
    estimator: Pipeline
    param_grid: dict[str, list[Any]]


# =============================================================================
# 2. BASIC UTILITIES
# =============================================================================

def normalise_event_id(value: Any) -> str:
    text = str(value).strip()
    if text.endswith(".0"):
        text = text[:-2]
    return text


def to_bool_series(series: pd.Series) -> pd.Series:
    if pd.api.types.is_bool_dtype(series):
        return series.fillna(False).astype(bool)
    return (
        series.fillna(False)
        .astype(str)
        .str.strip()
        .str.lower()
        .isin(TRUE_TEXT)
    )


def json_ready(value: Any) -> Any:
    if isinstance(value, Path):
        return str(value)
    if isinstance(value, pd.Timestamp):
        return value.isoformat()
    if isinstance(value, np.integer):
        return int(value)
    if isinstance(value, np.floating):
        return None if not np.isfinite(value) else float(value)
    if isinstance(value, np.bool_):
        return bool(value)
    if isinstance(value, dict):
        return {str(k): json_ready(v) for k, v in value.items()}
    if isinstance(value, (list, tuple)):
        return [json_ready(v) for v in value]
    try:
        if pd.isna(value):
            return None
    except (TypeError, ValueError):
        pass
    return value


def write_json(path: Path, payload: dict[str, Any]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8") as file:
        json.dump(json_ready(payload), file, ensure_ascii=False, indent=2)


def safe_divide(numerator: pd.Series, denominator: pd.Series) -> pd.Series:
    numerator = pd.to_numeric(numerator, errors="coerce").fillna(0.0)
    denominator = pd.to_numeric(denominator, errors="coerce")
    result = numerator / denominator.replace(0, np.nan)
    return result.replace([np.inf, -np.inf], np.nan).fillna(0.0)


def resolve_input_file(
    input_dir: Path,
    explicit: Optional[Path],
    standard_name: str,
    wildcard: str,
    required: bool = True,
) -> Optional[Path]:
    if explicit is not None:
        if not explicit.exists():
            raise FileNotFoundError(f"Input file not found: {explicit}")
        return explicit

    exact = input_dir / standard_name
    if exact.exists():
        return exact

    matches = sorted(
        input_dir.glob(wildcard),
        key=lambda p: (p.stat().st_mtime, p.name),
        reverse=True,
    )
    if matches:
        warnings.warn(
            f"{standard_name} was not found; using {matches[0].name} instead.",
            RuntimeWarning,
        )
        return matches[0]

    if required:
        raise FileNotFoundError(
            f"Could not find {standard_name} in {input_dir}. "
            f"Also tried wildcard {wildcard!r}."
        )
    return None


def merge_intervals(
    intervals: Iterable[tuple[pd.Timestamp, pd.Timestamp]],
) -> list[tuple[pd.Timestamp, pd.Timestamp]]:
    clean = sorted(
        [
            (pd.Timestamp(start), pd.Timestamp(end))
            for start, end in intervals
            if pd.notna(start)
            and pd.notna(end)
            and pd.Timestamp(end) > pd.Timestamp(start)
        ],
        key=lambda item: (item[0], item[1]),
    )
    if not clean:
        return []

    merged: list[tuple[pd.Timestamp, pd.Timestamp]] = []
    current_start, current_end = clean[0]
    for start, end in clean[1:]:
        if start <= current_end:
            current_end = max(current_end, end)
        else:
            merged.append((current_start, current_end))
            current_start, current_end = start, end
    merged.append((current_start, current_end))
    return merged


def interval_hours(
    intervals: Iterable[tuple[pd.Timestamp, pd.Timestamp]],
) -> float:
    return float(
        sum((end - start).total_seconds() / 3600.0 for start, end in intervals)
    )


def clip_interval(
    start: pd.Timestamp,
    end: pd.Timestamp,
    lower: pd.Timestamp,
    upper: pd.Timestamp,
) -> Optional[tuple[pd.Timestamp, pd.Timestamp]]:
    start = max(pd.Timestamp(start), pd.Timestamp(lower))
    end = min(pd.Timestamp(end), pd.Timestamp(upper))
    if end <= start:
        return None
    return start, end


# =============================================================================
# 3. LOAD AND STANDARDISE DATA
# =============================================================================

def load_feature_table(path: Path) -> pd.DataFrame:
    df = pd.read_csv(path, low_memory=False)
    required = {
        "event_id",
        "metadata_label",
        "metadata_start",
        "metadata_end",
        "event_duration_hours",
        "event_duration_days",
    }
    missing = sorted(required - set(df.columns))
    if missing:
        raise ValueError(
            f"Feature table is missing required columns: {missing}. "
            f"Available columns: {list(df.columns)}"
        )

    df = df.copy()
    df["event_id"] = df["event_id"].map(normalise_event_id)
    df["metadata_label"] = (
        df["metadata_label"].astype(str).str.strip().str.lower()
    )
    df["metadata_start"] = pd.to_datetime(
        df["metadata_start"], errors="coerce"
    )
    df["metadata_end"] = pd.to_datetime(df["metadata_end"], errors="coerce")

    df = df.loc[df["metadata_label"].isin(TARGET_MAP)].copy()
    df = df.dropna(subset=["metadata_start", "metadata_end"])
    df = df.drop_duplicates(subset=["event_id"], keep="last")
    df = df.reset_index(drop=True)

    if df.empty:
        raise ValueError("No labelled normal/anomaly events remain after cleaning.")

    return df


def load_segment_table(path: Path) -> pd.DataFrame:
    df = pd.read_csv(path, low_memory=False)
    if df.empty:
        return df

    required = {"event_id", "segment_start", "segment_end"}
    missing = sorted(required - set(df.columns))
    if missing:
        raise ValueError(f"Segment table {path.name} is missing: {missing}")

    df = df.copy()
    df["event_id"] = df["event_id"].map(normalise_event_id)
    df["segment_start"] = pd.to_datetime(df["segment_start"], errors="coerce")
    df["segment_end"] = pd.to_datetime(df["segment_end"], errors="coerce")
    df = df.dropna(subset=["segment_start", "segment_end"])
    df = df.loc[df["segment_end"] > df["segment_start"]].copy()

    for column in [
        "include_in_final",
        "power_confirmation_passed",
        "power_dip_near_start",
        "power_recovery_near_end",
        "long_power_recovery_confirmed",
        "power_evidence_available",
        "power_evidence_confirmed",
    ]:
        if column in df.columns:
            df[column] = to_bool_series(df[column])

    return df


def load_timeline_table(path: Optional[Path]) -> pd.DataFrame:
    if path is None:
        return pd.DataFrame()
    df = pd.read_csv(path, low_memory=False)
    if df.empty:
        return df

    required = {"event_id", "event_start", "event_end"}
    missing = sorted(required - set(df.columns))
    if missing:
        raise ValueError(f"Timeline table {path.name} is missing: {missing}")

    df = df.copy()
    df["event_id"] = df["event_id"].map(normalise_event_id)
    df["event_start"] = pd.to_datetime(df["event_start"], errors="coerce")
    df["event_end"] = pd.to_datetime(df["event_end"], errors="coerce")
    df = df.dropna(subset=["event_start", "event_end"])
    df = df.loc[df["event_end"] > df["event_start"]].copy()
    return df


# =============================================================================
# 4. RAW-SEGMENT FEATURE ENGINEERING
# =============================================================================

def numeric_summary(
    group: pd.DataFrame,
    columns: list[str],
    prefix: str,
) -> dict[str, float]:
    output: dict[str, float] = {}
    for column in columns:
        if column not in group.columns:
            continue
        values = pd.to_numeric(group[column], errors="coerce").dropna()
        clean_name = column.replace("_max", "").replace("_median", "")
        if values.empty:
            output[f"{prefix}_{clean_name}_mean"] = 0.0
            output[f"{prefix}_{clean_name}_max"] = 0.0
            continue
        output[f"{prefix}_{clean_name}_mean"] = float(values.mean())
        output[f"{prefix}_{clean_name}_max"] = float(values.max())
    return output


def union_duration_by_event(
    group: pd.DataFrame,
    event_start: pd.Timestamp,
    event_end: pd.Timestamp,
    start_column: str = "segment_start",
    end_column: str = "segment_end",
) -> float:
    intervals: list[tuple[pd.Timestamp, pd.Timestamp]] = []
    for _, row in group.iterrows():
        clipped = clip_interval(
            row[start_column], row[end_column], event_start, event_end
        )
        if clipped is not None:
            intervals.append(clipped)
    return interval_hours(merge_intervals(intervals))


def aggregate_raw_segments(
    raw: pd.DataFrame,
    event_bounds: pd.DataFrame,
) -> pd.DataFrame:
    if raw.empty:
        return pd.DataFrame({"event_id": event_bounds["event_id"]})

    bounds = event_bounds.set_index("event_id")
    rows: list[dict[str, Any]] = []

    for event_id, group in raw.groupby("event_id", sort=False):
        if event_id not in bounds.index:
            continue

        event_start = pd.Timestamp(bounds.loc[event_id, "metadata_start"])
        event_end = pd.Timestamp(bounds.loc[event_id, "metadata_end"])
        event_hours = max(
            float(bounds.loc[event_id, "event_duration_hours"]), 1e-9
        )

        result: dict[str, Any] = {"event_id": event_id}

        detector = group.get("detector", pd.Series("", index=group.index)).astype(str)
        short = group.loc[detector == "short_standstill"].copy()
        persistent = group.loc[detector == "persistent_system_state"].copy()
        localized = group.loc[
            detector == "localized_persistent_subsystem_state"
        ].copy()

        if not localized.empty and "include_in_final" in localized.columns:
            confirmed_localized = localized.loc[localized["include_in_final"]].copy()
            rejected_localized = localized.loc[~localized["include_in_final"]].copy()
        else:
            confirmed_localized = pd.DataFrame(columns=localized.columns)
            rejected_localized = localized.copy()

        result["raw_short_segment_count"] = int(len(short))
        result["raw_persistent_segment_count"] = int(len(persistent))
        result["raw_confirmed_localized_count"] = int(len(confirmed_localized))
        result["raw_rejected_localized_count"] = int(len(rejected_localized))

        result.update(
            numeric_summary(
                short,
                [
                    "duration_minutes",
                    "detector_score_max",
                    "abnormal_fraction_max",
                    "power_dip_signal_count_max",
                    "power_recovery_signal_count_max",
                    "power_variability_signal_count_max",
                    "power_dip_score_max",
                    "power_recovery_score_max",
                    "power_variability_score_max",
                ],
                "raw_short",
            )
        )

        if not short.empty:
            required = np.ceil(
                0.75
                * pd.to_numeric(short.get("power_signal_count", 0), errors="coerce")
                .fillna(0)
            )
            required = np.maximum(required, 1)
            recovery_count = pd.to_numeric(
                short.get("power_recovery_signal_count_max", 0), errors="coerce"
            ).fillna(0)
            variability_count = pd.to_numeric(
                short.get("power_variability_signal_count_max", 0), errors="coerce"
            ).fillna(0)
            result["raw_short_direct_recovery_fraction"] = float(
                (recovery_count >= required).mean()
            )
            result["raw_short_variability_support_fraction"] = float(
                (variability_count >= required).mean()
            )
        else:
            result["raw_short_direct_recovery_fraction"] = 0.0
            result["raw_short_variability_support_fraction"] = 0.0

        result.update(
            numeric_summary(
                persistent,
                [
                    "duration_minutes",
                    "detector_score_max",
                    "abnormal_fraction_max",
                    "mean_active_signal_count",
                    "max_active_signal_count",
                ],
                "raw_persistent",
            )
        )

        for local_name, local_group in [
            ("confirmed_localized", confirmed_localized),
            ("rejected_localized", rejected_localized),
        ]:
            result.update(
                numeric_summary(
                    local_group,
                    [
                        "duration_minutes",
                        "detector_score_max",
                        "abnormal_fraction_max",
                        "dominant_signal_count",
                        "mean_active_signal_count",
                        "max_active_signal_count",
                        "mean_stable_signal_count",
                        "max_stable_signal_count",
                        "mean_sensor_set_overlap",
                        "long_power_dip_signal_count",
                        "long_power_recovery_signal_count",
                        "long_power_drop_ratio_median",
                        "long_power_recovery_ratio_median",
                        "boundary_power_dip_signal_count_max",
                        "boundary_power_recovery_signal_count_max",
                    ],
                    local_name,
                )
            )

            union_hours = union_duration_by_event(
                local_group, event_start, event_end
            )
            result[f"{local_name}_union_hours"] = union_hours
            result[f"{local_name}_coverage_fraction"] = min(
                1.0, union_hours / event_hours
            )

        if not rejected_localized.empty:
            rejection_reason = rejected_localized.get(
                "rejection_reason", pd.Series("", index=rejected_localized.index)
            ).fillna("").astype(str)
            result["rejected_missing_start_count"] = int(
                (rejection_reason == "missing_start_power_dip").sum()
            )
            result["rejected_missing_end_count"] = int(
                (rejection_reason == "missing_end_power_recovery").sum()
            )
            result["rejected_missing_both_count"] = int(
                (
                    rejection_reason
                    == "missing_start_power_dip_and_end_power_recovery"
                ).sum()
            )
            result["rejected_power_unavailable_count"] = int(
                (rejection_reason == "power_evidence_unavailable").sum()
            )

            if "power_dip_near_start" in rejected_localized.columns:
                result["rejected_start_dip_fraction"] = float(
                    rejected_localized["power_dip_near_start"].mean()
                )
            else:
                result["rejected_start_dip_fraction"] = 0.0

            if "power_recovery_near_end" in rejected_localized.columns:
                result["rejected_end_recovery_fraction"] = float(
                    rejected_localized["power_recovery_near_end"].mean()
                )
            else:
                result["rejected_end_recovery_fraction"] = 0.0
        else:
            for column in [
                "rejected_missing_start_count",
                "rejected_missing_end_count",
                "rejected_missing_both_count",
                "rejected_power_unavailable_count",
            ]:
                result[column] = 0
            result["rejected_start_dip_fraction"] = 0.0
            result["rejected_end_recovery_fraction"] = 0.0

        rows.append(result)

    aggregated = pd.DataFrame(rows)
    all_events = event_bounds[["event_id"]].drop_duplicates()
    return all_events.merge(aggregated, on="event_id", how="left").fillna(0.0)


# =============================================================================
# 5. FINAL-TIMELINE FEATURE ENGINEERING
# =============================================================================

def aggregate_timeline(
    timeline: pd.DataFrame,
    event_bounds: pd.DataFrame,
) -> pd.DataFrame:
    if timeline.empty:
        return pd.DataFrame({"event_id": event_bounds["event_id"]})

    bounds = event_bounds.set_index("event_id")
    rows: list[dict[str, Any]] = []

    for event_id, group in timeline.groupby("event_id", sort=False):
        if event_id not in bounds.index:
            continue
        event_start = pd.Timestamp(bounds.loc[event_id, "metadata_start"])
        event_end = pd.Timestamp(bounds.loc[event_id, "metadata_end"])
        event_hours = max(
            float(bounds.loc[event_id, "event_duration_hours"]), 1e-9
        )

        result: dict[str, Any] = {"event_id": event_id}
        group = group.copy()
        group["duration_hours_clipped"] = group.apply(
            lambda row: (
                (clip_interval(row["event_start"], row["event_end"], event_start, event_end)[1]
                 - clip_interval(row["event_start"], row["event_end"], event_start, event_end)[0])
                .total_seconds()
                / 3600.0
                if clip_interval(
                    row["event_start"], row["event_end"], event_start, event_end
                )
                is not None
                else 0.0
            ),
            axis=1,
        )

        n_detectors = pd.to_numeric(group.get("n_detectors", 0), errors="coerce").fillna(0)
        overlap = group.loc[n_detectors >= 2]
        result["timeline_interval_count"] = int(len(group))
        result["timeline_multi_detector_interval_count"] = int(len(overlap))
        result["timeline_max_detector_count"] = float(n_detectors.max()) if len(group) else 0.0
        result["timeline_mean_detector_count"] = float(n_detectors.mean()) if len(group) else 0.0
        result["timeline_confirmed_union_hours"] = float(
            group["duration_hours_clipped"].sum()
        )
        result["timeline_confirmed_coverage_fraction"] = min(
            1.0, result["timeline_confirmed_union_hours"] / event_hours
        )
        result["timeline_multi_detector_hours"] = float(
            overlap["duration_hours_clipped"].sum()
        )
        result["timeline_multi_detector_coverage_fraction"] = min(
            1.0, result["timeline_multi_detector_hours"] / event_hours
        )

        for column in [
            "mean_smoothed_score",
            "mean_abnormal_fraction",
            "contained_short_standstill_count",
            "mean_short_standstill_fraction",
            "mean_intermittent_short_flag_density",
            "mean_persistent_system_fraction",
            "mean_localized_active_fraction",
            "mean_localized_stable_signal_count",
            "mean_localized_sensor_set_overlap",
            "localized_long_power_recovery_ratio_median",
            "localized_long_power_dip_signal_count_max",
            "localized_long_power_recovery_signal_count_max",
        ]:
            if column not in group.columns:
                continue
            values = pd.to_numeric(group[column], errors="coerce").dropna()
            result[f"timeline_{column}_mean"] = float(values.mean()) if not values.empty else 0.0
            result[f"timeline_{column}_max"] = float(values.max()) if not values.empty else 0.0

        rows.append(result)

    aggregated = pd.DataFrame(rows)
    all_events = event_bounds[["event_id"]].drop_duplicates()
    return all_events.merge(aggregated, on="event_id", how="left").fillna(0.0)


# =============================================================================
# 6. COMBINED EVENT-LEVEL DATASET
# =============================================================================

def create_model_dataset(
    feature_table: pd.DataFrame,
    raw_segments: pd.DataFrame,
    timeline: pd.DataFrame,
) -> tuple[pd.DataFrame, pd.Series, pd.DataFrame, list[str]]:
    base = feature_table.copy()
    event_bounds = base[
        [
            "event_id",
            "metadata_start",
            "metadata_end",
            "event_duration_hours",
            "event_duration_days",
        ]
    ].copy()

    raw_features = aggregate_raw_segments(raw_segments, event_bounds)
    timeline_features = aggregate_timeline(timeline, event_bounds)

    data = base.merge(raw_features, on="event_id", how="left")
    data = data.merge(timeline_features, on="event_id", how="left")

    # Rates and coverage fractions use duration only as a denominator. The raw
    # duration columns are later excluded from X.
    event_hours = pd.to_numeric(data["event_duration_hours"], errors="coerce").fillna(0.0)
    event_days = pd.to_numeric(data["event_duration_days"], errors="coerce").fillna(0.0)

    data["persistent_coverage_fraction"] = safe_divide(
        data.get("total_persistent_hours", 0), event_hours
    ).clip(0, 1)
    data["confirmed_localized_coverage_fraction"] = safe_divide(
        data.get("total_confirmed_localized_hours", 0), event_hours
    ).clip(0, 1)
    data["rejected_localized_feature_coverage_fraction"] = safe_divide(
        data.get("total_rejected_localized_hours", 0), event_hours
    ).clip(0, 1)
    data["strong_cluster_rate_per_day"] = safe_divide(
        data.get("strong_cluster_count", 0), event_days
    )
    data["weak_cluster_rate_per_day"] = safe_divide(
        data.get("weak_cluster_count", 0), event_days
    )
    data["persistent_segment_rate_per_day"] = safe_divide(
        data.get("persistent_segment_count", 0), event_days
    )
    data["rejected_localized_rate_per_day"] = safe_divide(
        data.get("rejected_localized_candidate_count", 0), event_days
    )

    short_count = pd.to_numeric(
        data.get("short_episode_count", 0), errors="coerce"
    ).fillna(0.0)
    data["direct_recovery_short_ratio"] = safe_divide(
        data.get("direct_recovery_short_episode_count", 0), short_count
    )
    data["variability_only_short_ratio"] = safe_divide(
        data.get("variability_only_short_episode_count", 0), short_count
    )

    # Log transforms reduce domination by a few extremely long events while
    # retaining the information contained in duration/count features.
    log_candidates = [
        "short_episode_count",
        "max_short_count_2h",
        "max_short_count_24h",
        "weak_cluster_count",
        "strong_cluster_count",
        "persistent_segment_count",
        "max_persistent_hours",
        "total_persistent_hours",
        "confirmed_localized_segment_count",
        "max_confirmed_localized_hours",
        "total_confirmed_localized_hours",
        "rejected_localized_candidate_count",
        "max_rejected_localized_hours",
        "total_rejected_localized_hours",
        "raw_short_segment_count",
        "raw_persistent_segment_count",
        "raw_confirmed_localized_count",
        "raw_rejected_localized_count",
        "rejected_localized_union_hours",
        "confirmed_localized_union_hours",
    ]
    for column in log_candidates:
        if column in data.columns:
            values = pd.to_numeric(data[column], errors="coerce").fillna(0.0)
            data[f"log1p_{column}"] = np.log1p(values.clip(lower=0.0))

    y = data["metadata_label"].map(TARGET_MAP).astype(int)

    # Convert booleans to 0/1 before selecting numeric columns.
    for column in data.columns:
        if pd.api.types.is_bool_dtype(data[column]):
            data[column] = data[column].astype(int)
        elif data[column].dtype == object:
            lower_values = data[column].dropna().astype(str).str.lower().unique()
            if len(lower_values) > 0 and set(lower_values).issubset(TRUE_TEXT | {"false", "0", "no", "n", "f"}):
                data[column] = to_bool_series(data[column]).astype(int)

    candidate_columns = [
        column
        for column in MODEL_FEATURE_COLUMNS
        if column in data.columns
        and column not in LEAKAGE_OR_ID_COLUMNS
        and pd.api.types.is_numeric_dtype(data[column])
    ]

    # Remove all-empty and constant features. This is done before CV only for
    # deterministic structural columns, not using label information.
    X = data[candidate_columns].apply(pd.to_numeric, errors="coerce")
    all_empty = X.columns[X.isna().all()].tolist()
    X = X.drop(columns=all_empty)
    constant = [
        column
        for column in X.columns
        if X[column].nunique(dropna=True) <= 1
    ]
    X = X.drop(columns=constant)

    if X.empty:
        raise ValueError("No usable numeric event-level features were created.")

    metadata = data[
        ["event_id", "metadata_label", "metadata_start", "metadata_end"]
    ].copy()
    excluded_structural = all_empty + constant
    return X, y, metadata, excluded_structural


# =============================================================================
# 7. MODELS, THRESHOLD TUNING AND METRICS
# =============================================================================

def build_model_specs(random_state: int) -> list[ModelSpec]:
    logistic = Pipeline(
        steps=[
            ("imputer", SimpleImputer(strategy="median")),
            ("scaler", RobustScaler()),
            (
                "model",
                LogisticRegression(
                    solver="liblinear",
                    class_weight="balanced",
                    max_iter=3000,
                    random_state=random_state,
                ),
            ),
        ]
    )

    tree = Pipeline(
        steps=[
            ("imputer", SimpleImputer(strategy="median")),
            (
                "model",
                DecisionTreeClassifier(
                    class_weight="balanced",
                    random_state=random_state,
                ),
            ),
        ]
    )

    forest = Pipeline(
        steps=[
            ("imputer", SimpleImputer(strategy="median")),
            (
                "model",
                RandomForestClassifier(
                    n_estimators=120,
                    class_weight="balanced_subsample",
                    n_jobs=1,
                    random_state=random_state,
                ),
            ),
        ]
    )

    return [
        ModelSpec(
            name="logistic_regression",
            estimator=logistic,
            param_grid={
                "model__C": [0.03, 0.1, 0.3, 1.0, 3.0],
            },
        ),
        ModelSpec(
            name="shallow_decision_tree",
            estimator=tree,
            param_grid={
                "model__max_depth": [2, 3, 4],
                "model__min_samples_leaf": [4, 7],
            },
        ),
        ModelSpec(
            name="restricted_random_forest",
            estimator=forest,
            param_grid={
                "model__max_depth": [2, 3],
                "model__min_samples_leaf": [4, 6],
                "model__max_features": ["sqrt"],
            },
        ),
    ]


def calculate_binary_metrics(
    y_true: np.ndarray | pd.Series,
    y_pred: np.ndarray | pd.Series,
    probabilities: Optional[np.ndarray | pd.Series] = None,
) -> dict[str, float]:
    y_true = np.asarray(y_true, dtype=int)
    y_pred = np.asarray(y_pred, dtype=int)

    cm = confusion_matrix(y_true, y_pred, labels=[0, 1])
    tn, fp, fn, tp = cm.ravel()

    metrics = {
        "n": int(len(y_true)),
        "true_negative": int(tn),
        "false_positive": int(fp),
        "false_negative": int(fn),
        "true_positive": int(tp),
        "accuracy": float(accuracy_score(y_true, y_pred)),
        "balanced_accuracy": float(balanced_accuracy_score(y_true, y_pred)),
        "precision_anomaly": float(
            precision_score(y_true, y_pred, zero_division=0)
        ),
        "recall_anomaly": float(recall_score(y_true, y_pred, zero_division=0)),
        "f1_anomaly": float(f1_score(y_true, y_pred, zero_division=0)),
        "specificity_normal": float(tn / (tn + fp)) if (tn + fp) else np.nan,
        "normal_false_positive_rate": float(fp / (tn + fp))
        if (tn + fp)
        else np.nan,
    }

    if probabilities is not None and len(np.unique(y_true)) == 2:
        try:
            metrics["roc_auc"] = float(roc_auc_score(y_true, probabilities))
        except ValueError:
            metrics["roc_auc"] = np.nan
    else:
        metrics["roc_auc"] = np.nan

    return metrics


def select_probability_threshold(
    y_true: pd.Series | np.ndarray,
    probabilities: pd.Series | np.ndarray,
    max_normal_fpr: float,
) -> ThresholdResult:
    y_true = np.asarray(y_true, dtype=int)
    probabilities = np.asarray(probabilities, dtype=float)

    thresholds = np.round(np.arange(0.20, 0.801, 0.01), 2)
    candidates: list[ThresholdResult] = []

    for threshold in thresholds:
        predicted = (probabilities >= threshold).astype(int)
        metrics = calculate_binary_metrics(y_true, predicted, probabilities)
        fpr = metrics["normal_false_positive_rate"]
        combined = 0.50 * metrics["balanced_accuracy"] + 0.50 * metrics["f1_anomaly"]

        # Prefer thresholds satisfying the requested FPR limit. If none do,
        # penalise excess false positives smoothly instead of failing.
        penalty = max(0.0, fpr - max_normal_fpr)
        score = combined - 0.75 * penalty

        candidates.append(
            ThresholdResult(
                threshold=float(threshold),
                score=float(score),
                balanced_accuracy=float(metrics["balanced_accuracy"]),
                f1=float(metrics["f1_anomaly"]),
                recall=float(metrics["recall_anomaly"]),
                specificity=float(metrics["specificity_normal"]),
                normal_false_positive_rate=float(fpr),
            )
        )

    feasible = [
        candidate
        for candidate in candidates
        if candidate.normal_false_positive_rate <= max_normal_fpr
    ]
    pool = feasible if feasible else candidates

    # Maximise combined performance, then recall, then choose the threshold
    # closest to 0.5 to reduce unstable extreme thresholds.
    best = max(
        pool,
        key=lambda item: (
            item.score,
            item.balanced_accuracy,
            item.f1,
            item.recall,
            -abs(item.threshold - 0.5),
        ),
    )
    return best


def make_inner_cv(
    y: pd.Series,
    requested_splits: int,
    random_state: int,
) -> StratifiedKFold:
    minimum_class_count = int(y.value_counts().min())
    n_splits = max(2, min(requested_splits, minimum_class_count))
    return StratifiedKFold(
        n_splits=n_splits,
        shuffle=True,
        random_state=random_state,
    )


def tune_model_and_threshold(
    spec: ModelSpec,
    X_train: pd.DataFrame,
    y_train: pd.Series,
    inner_splits: int,
    random_state: int,
    max_normal_fpr: float,
) -> tuple[BaseEstimator, dict[str, Any], ThresholdResult]:
    inner_cv = make_inner_cv(y_train, inner_splits, random_state)

    search = GridSearchCV(
        estimator=clone(spec.estimator),
        param_grid=spec.param_grid,
        scoring="roc_auc",
        cv=inner_cv,
        n_jobs=1,
        refit=True,
        error_score="raise",
    )
    search.fit(X_train, y_train)

    best_estimator = search.best_estimator_

    # Out-of-fold probabilities on the outer training data are used to tune
    # the classification threshold. The outer test fold remains untouched.
    oof_probabilities = cross_val_predict(
        clone(best_estimator),
        X_train,
        y_train,
        cv=inner_cv,
        method="predict_proba",
        n_jobs=1,
    )[:, 1]

    threshold_result = select_probability_threshold(
        y_true=y_train,
        probabilities=oof_probabilities,
        max_normal_fpr=max_normal_fpr,
    )

    best_estimator.fit(X_train, y_train)
    return best_estimator, search.best_params_, threshold_result


# =============================================================================
# 8. REPEATED NESTED CROSS-VALIDATION
# =============================================================================

def run_repeated_nested_cv(
    X: pd.DataFrame,
    y: pd.Series,
    metadata: pd.DataFrame,
    specs: list[ModelSpec],
    cv_splits: int,
    cv_repeats: int,
    inner_splits: int,
    random_state: int,
    max_normal_fpr: float,
) -> tuple[pd.DataFrame, pd.DataFrame, pd.DataFrame]:
    minimum_class_count = int(y.value_counts().min())
    n_splits = max(2, min(cv_splits, minimum_class_count))

    outer_cv = RepeatedStratifiedKFold(
        n_splits=n_splits,
        n_repeats=cv_repeats,
        random_state=random_state,
    )

    fold_rows: list[dict[str, Any]] = []
    prediction_rows: list[dict[str, Any]] = []

    total_folds = n_splits * cv_repeats
    for spec in specs:
        print(f"[CV] Model: {spec.name}")
        for split_number, (train_idx, test_idx) in enumerate(
            outer_cv.split(X, y), start=1
        ):
            repeat_number = (split_number - 1) // n_splits + 1
            fold_number = (split_number - 1) % n_splits + 1

            X_train = X.iloc[train_idx]
            X_test = X.iloc[test_idx]
            y_train = y.iloc[train_idx]
            y_test = y.iloc[test_idx]

            seed = random_state + split_number * 100 + len(fold_rows)
            estimator, best_params, threshold_result = tune_model_and_threshold(
                spec=spec,
                X_train=X_train,
                y_train=y_train,
                inner_splits=inner_splits,
                random_state=seed,
                max_normal_fpr=max_normal_fpr,
            )

            probabilities = estimator.predict_proba(X_test)[:, 1]
            predicted = (probabilities >= threshold_result.threshold).astype(int)
            metrics = calculate_binary_metrics(y_test, predicted, probabilities)

            fold_rows.append(
                {
                    "model": spec.name,
                    "repeat": repeat_number,
                    "fold": fold_number,
                    "threshold": threshold_result.threshold,
                    "best_params": json.dumps(best_params, sort_keys=True),
                    **metrics,
                }
            )

            test_metadata = metadata.iloc[test_idx].reset_index(drop=True)
            for position in range(len(test_idx)):
                prediction_rows.append(
                    {
                        "model": spec.name,
                        "repeat": repeat_number,
                        "fold": fold_number,
                        "event_id": test_metadata.loc[position, "event_id"],
                        "metadata_start": test_metadata.loc[position, "metadata_start"],
                        "actual_label": LABEL_MAP[int(y_test.iloc[position])],
                        "actual_binary": int(y_test.iloc[position]),
                        "anomaly_probability": float(probabilities[position]),
                        "threshold": float(threshold_result.threshold),
                        "decision_margin": float(
                            probabilities[position] - threshold_result.threshold
                        ),
                        "predicted_binary": int(predicted[position]),
                        "predicted_label": LABEL_MAP[int(predicted[position])],
                    }
                )

            if split_number == 1 or split_number % max(1, n_splits) == 0:
                print(
                    f"  completed {split_number}/{total_folds} folds "
                    f"for {spec.name}"
                )

    fold_df = pd.DataFrame(fold_rows)
    repeated_predictions = pd.DataFrame(prediction_rows)

    comparison_rows: list[dict[str, Any]] = []
    metric_columns = [
        "accuracy",
        "balanced_accuracy",
        "precision_anomaly",
        "recall_anomaly",
        "f1_anomaly",
        "specificity_normal",
        "normal_false_positive_rate",
        "roc_auc",
        "threshold",
    ]

    for model_name, group in fold_df.groupby("model"):
        row: dict[str, Any] = {"model": model_name, "fold_count": len(group)}
        for metric in metric_columns:
            values = pd.to_numeric(group[metric], errors="coerce")
            row[f"mean_{metric}"] = float(values.mean())
            row[f"std_{metric}"] = float(values.std(ddof=1))
        comparison_rows.append(row)

    comparison = pd.DataFrame(comparison_rows).sort_values(
        ["mean_balanced_accuracy", "mean_f1_anomaly", "mean_roc_auc"],
        ascending=False,
    )

    return fold_df, repeated_predictions, comparison


def aggregate_repeated_predictions(
    repeated_predictions: pd.DataFrame,
) -> pd.DataFrame:
    rows: list[dict[str, Any]] = []

    for (model_name, event_id), group in repeated_predictions.groupby(
        ["model", "event_id"], sort=False
    ):
        mean_margin = float(group["decision_margin"].mean())
        predicted_binary = int(mean_margin >= 0.0)
        rows.append(
            {
                "model": model_name,
                "event_id": event_id,
                "metadata_start": group["metadata_start"].iloc[0],
                "actual_label": group["actual_label"].iloc[0],
                "actual_binary": int(group["actual_binary"].iloc[0]),
                "cv_prediction_count": int(len(group)),
                "mean_anomaly_probability": float(
                    group["anomaly_probability"].mean()
                ),
                "std_anomaly_probability": float(
                    group["anomaly_probability"].std(ddof=1)
                )
                if len(group) > 1
                else 0.0,
                "mean_threshold": float(group["threshold"].mean()),
                "mean_decision_margin": mean_margin,
                "anomaly_vote_fraction": float(
                    group["predicted_binary"].mean()
                ),
                "predicted_binary": predicted_binary,
                "predicted_label": LABEL_MAP[predicted_binary],
                "prediction_correct": bool(
                    predicted_binary == int(group["actual_binary"].iloc[0])
                ),
            }
        )

    return pd.DataFrame(rows)


def select_final_model_name(
    comparison: pd.DataFrame,
    interpretability_tolerance: float,
) -> str:
    if comparison.empty:
        raise ValueError("Model comparison is empty.")

    top_row = comparison.iloc[0]
    top_name = str(top_row["model"])
    top_score = float(top_row["mean_balanced_accuracy"])

    logistic_rows = comparison.loc[
        comparison["model"] == "logistic_regression"
    ]
    if not logistic_rows.empty:
        logistic_score = float(
            logistic_rows.iloc[0]["mean_balanced_accuracy"]
        )
        if top_score - logistic_score <= interpretability_tolerance:
            return "logistic_regression"

    return top_name


# =============================================================================
# 9. FINAL FIT, IMPORTANCE AND EXPLANATIONS
# =============================================================================

def extract_feature_importance(
    estimator: Pipeline,
    feature_names: list[str],
) -> pd.DataFrame:
    model = estimator.named_steps["model"]

    if hasattr(model, "coef_"):
        values = np.asarray(model.coef_[0], dtype=float)
        importance_type = "logistic_coefficient"
    elif hasattr(model, "feature_importances_"):
        values = np.asarray(model.feature_importances_, dtype=float)
        importance_type = "tree_feature_importance"
    else:
        return pd.DataFrame(
            columns=["feature", "importance", "absolute_importance", "importance_type"]
        )

    result = pd.DataFrame(
        {
            "feature": feature_names,
            "importance": values,
            "absolute_importance": np.abs(values),
            "importance_type": importance_type,
        }
    )
    return result.sort_values("absolute_importance", ascending=False).reset_index(drop=True)


def build_event_explanations(
    estimator: Pipeline,
    X: pd.DataFrame,
    metadata: pd.DataFrame,
    probabilities: np.ndarray,
    threshold: float,
    importance: pd.DataFrame,
    top_n: int = 5,
) -> pd.DataFrame:
    model = estimator.named_steps["model"]
    rows: list[dict[str, Any]] = []

    if hasattr(model, "coef_"):
        imputed = estimator.named_steps["imputer"].transform(X)
        scaled = estimator.named_steps["scaler"].transform(imputed)
        coefficients = np.asarray(model.coef_[0], dtype=float)
        contributions = scaled * coefficients

        for index in range(len(X)):
            contribution_row = contributions[index]
            positive_idx = np.argsort(contribution_row)[::-1][:top_n]
            negative_idx = np.argsort(contribution_row)[:top_n]

            positive = "; ".join(
                f"{X.columns[i]}={contribution_row[i]:+.3f}"
                for i in positive_idx
                if contribution_row[i] > 0
            )
            negative = "; ".join(
                f"{X.columns[i]}={contribution_row[i]:+.3f}"
                for i in negative_idx
                if contribution_row[i] < 0
            )

            predicted_binary = int(probabilities[index] >= threshold)
            rows.append(
                {
                    "event_id": metadata.iloc[index]["event_id"],
                    "actual_label": metadata.iloc[index]["metadata_label"],
                    "anomaly_probability": float(probabilities[index]),
                    "threshold": float(threshold),
                    "predicted_label": LABEL_MAP[predicted_binary],
                    "main_supporting_features": positive,
                    "main_opposing_features": negative,
                    "explanation_method": "logistic_local_contribution",
                }
            )
    else:
        global_top = "; ".join(
            importance.head(top_n)["feature"].astype(str).tolist()
        )
        for index in range(len(X)):
            predicted_binary = int(probabilities[index] >= threshold)
            rows.append(
                {
                    "event_id": metadata.iloc[index]["event_id"],
                    "actual_label": metadata.iloc[index]["metadata_label"],
                    "anomaly_probability": float(probabilities[index]),
                    "threshold": float(threshold),
                    "predicted_label": LABEL_MAP[predicted_binary],
                    "main_supporting_features": global_top,
                    "main_opposing_features": "",
                    "explanation_method": "global_tree_importance",
                }
            )

    return pd.DataFrame(rows)


def train_final_model(
    selected_spec: ModelSpec,
    X: pd.DataFrame,
    y: pd.Series,
    inner_splits: int,
    random_state: int,
    max_normal_fpr: float,
) -> tuple[Pipeline, dict[str, Any], ThresholdResult, np.ndarray]:
    estimator, best_params, threshold_result = tune_model_and_threshold(
        spec=selected_spec,
        X_train=X,
        y_train=y,
        inner_splits=inner_splits,
        random_state=random_state,
        max_normal_fpr=max_normal_fpr,
    )
    probabilities = estimator.predict_proba(X)[:, 1]
    return estimator, best_params, threshold_result, probabilities


# =============================================================================
# 10. CHRONOLOGICAL HOLDOUT
# =============================================================================

def run_time_holdout(
    spec: ModelSpec,
    X: pd.DataFrame,
    y: pd.Series,
    metadata: pd.DataFrame,
    test_fraction: float,
    inner_splits: int,
    random_state: int,
    max_normal_fpr: float,
) -> tuple[pd.DataFrame, dict[str, Any]]:
    order = np.argsort(pd.to_datetime(metadata["metadata_start"]).to_numpy())
    test_count = max(1, int(math.ceil(len(X) * test_fraction)))
    train_idx = order[:-test_count]
    test_idx = order[-test_count:]

    if len(train_idx) < 10 or y.iloc[train_idx].nunique() < 2:
        return pd.DataFrame(), {
            "status": "skipped",
            "reason": "Chronological training subset was too small or had one class.",
        }

    X_train = X.iloc[train_idx]
    y_train = y.iloc[train_idx]
    X_test = X.iloc[test_idx]
    y_test = y.iloc[test_idx]

    estimator, best_params, threshold_result = tune_model_and_threshold(
        spec=spec,
        X_train=X_train,
        y_train=y_train,
        inner_splits=inner_splits,
        random_state=random_state,
        max_normal_fpr=max_normal_fpr,
    )

    probabilities = estimator.predict_proba(X_test)[:, 1]
    predicted = (probabilities >= threshold_result.threshold).astype(int)
    metrics = calculate_binary_metrics(y_test, predicted, probabilities)
    metrics.update(
        {
            "status": "success",
            "train_events": int(len(train_idx)),
            "test_events": int(len(test_idx)),
            "threshold": threshold_result.threshold,
            "best_params": best_params,
            "training_start": metadata.iloc[train_idx]["metadata_start"].min(),
            "training_end": metadata.iloc[train_idx]["metadata_start"].max(),
            "test_start": metadata.iloc[test_idx]["metadata_start"].min(),
            "test_end": metadata.iloc[test_idx]["metadata_start"].max(),
        }
    )

    predictions = metadata.iloc[test_idx].copy().reset_index(drop=True)
    predictions["actual_binary"] = y_test.to_numpy()
    predictions["actual_label"] = predictions["actual_binary"].map(LABEL_MAP)
    predictions["anomaly_probability"] = probabilities
    predictions["threshold"] = threshold_result.threshold
    predictions["predicted_binary"] = predicted
    predictions["predicted_label"] = predictions["predicted_binary"].map(LABEL_MAP)
    predictions["prediction_correct"] = (
        predictions["actual_binary"] == predictions["predicted_binary"]
    )

    return predictions, metrics


# =============================================================================
# 11. BASELINE COMPARISON
# =============================================================================

def evaluate_rule_baseline(path: Optional[Path]) -> Optional[dict[str, Any]]:
    if path is None or not path.exists():
        return None
    df = pd.read_csv(path, low_memory=False)
    required = {"metadata_label", "binary_decision"}
    if not required.issubset(df.columns):
        return None

    actual = (
        df["metadata_label"].astype(str).str.lower().map(TARGET_MAP)
    )
    predicted = (
        df["binary_decision"].astype(str).str.lower().map(TARGET_MAP)
    )
    valid = actual.notna() & predicted.notna()
    if not valid.any():
        return None
    return calculate_binary_metrics(
        actual.loc[valid].astype(int),
        predicted.loc[valid].astype(int),
    )


# =============================================================================
# 12. PLOTS
# =============================================================================

def save_plots(
    comparison: pd.DataFrame,
    selected_predictions: pd.DataFrame,
    output_dir: Path,
) -> None:
    if not comparison.empty:
        fig, ax = plt.subplots(figsize=(9, 5))
        ordered = comparison.sort_values("mean_balanced_accuracy")
        ax.barh(ordered["model"], ordered["mean_balanced_accuracy"])
        ax.set_xlabel("Mean outer-fold balanced accuracy")
        ax.set_ylabel("Model")
        ax.set_title("Event-level model comparison")
        ax.set_xlim(0, 1)
        fig.tight_layout()
        fig.savefig(output_dir / "model_comparison_balanced_accuracy.png", dpi=160)
        plt.close(fig)

    if not selected_predictions.empty:
        actual = selected_predictions["actual_binary"].astype(int)
        predicted = selected_predictions["predicted_binary"].astype(int)
        cm = confusion_matrix(actual, predicted, labels=[0, 1])

        fig, ax = plt.subplots(figsize=(5.5, 5))
        image = ax.imshow(cm)
        ax.set_xticks([0, 1], labels=["normal", "anomaly"])
        ax.set_yticks([0, 1], labels=["normal", "anomaly"])
        ax.set_xlabel("Predicted")
        ax.set_ylabel("Actual")
        ax.set_title("Aggregated repeated-CV confusion matrix")
        for row in range(2):
            for col in range(2):
                ax.text(col, row, str(cm[row, col]), ha="center", va="center")
        fig.colorbar(image, ax=ax)
        fig.tight_layout()
        fig.savefig(output_dir / "selected_model_confusion_matrix.png", dpi=160)
        plt.close(fig)

        fig, ax = plt.subplots(figsize=(9, 5))
        for label, group in selected_predictions.groupby("actual_label"):
            ax.hist(
                group["mean_anomaly_probability"],
                bins=np.linspace(0, 1, 16),
                alpha=0.55,
                label=str(label),
            )
        ax.set_xlabel("Mean repeated-CV anomaly probability")
        ax.set_ylabel("Number of events")
        ax.set_title("Cross-validated event probability distribution")
        ax.legend()
        fig.tight_layout()
        fig.savefig(output_dir / "selected_model_probability_distribution.png", dpi=160)
        plt.close(fig)


# =============================================================================
# 13. COMMAND LINE
# =============================================================================

def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description=(
            "Train and evaluate an event-level machine-learning classifier "
            "from four-detector output tables."
        )
    )
    parser.add_argument(
        "--input-dir",
        type=Path,
        required=True,
        help="Directory containing the all_events_*.csv detector outputs.",
    )
    parser.add_argument(
        "--features-file",
        type=Path,
        default=None,
        help="Optional explicit all_events_event_level_features.csv path.",
    )
    parser.add_argument(
        "--raw-segments-file",
        type=Path,
        default=None,
        help="Optional explicit all_events_detected_segments_raw.csv path.",
    )
    parser.add_argument(
        "--timeline-segments-file",
        type=Path,
        default=None,
        help="Optional explicit all_events_detected_segments.csv path.",
    )
    parser.add_argument(
        "--baseline-decisions-file",
        type=Path,
        default=None,
        help="Optional previous all_events_event_level_decisions.csv path.",
    )
    parser.add_argument(
        "--output-dir",
        type=Path,
        required=True,
        help="Directory to receive model, metrics and predictions.",
    )
    parser.add_argument("--cv-splits", type=int, default=5)
    parser.add_argument("--cv-repeats", type=int, default=5)
    parser.add_argument("--inner-splits", type=int, default=3)
    parser.add_argument("--random-state", type=int, default=42)
    parser.add_argument(
        "--max-normal-fpr",
        type=float,
        default=0.25,
        help=(
            "Preferred upper normal false-positive rate while selecting the "
            "probability threshold. Default: 0.25."
        ),
    )
    parser.add_argument(
        "--interpretability-tolerance",
        type=float,
        default=0.03,
        help=(
            "Prefer Logistic Regression when its mean balanced accuracy is "
            "within this value of the best model. Default: 0.03."
        ),
    )
    parser.add_argument(
        "--time-test-fraction",
        type=float,
        default=0.20,
        help="Fraction of latest events used for chronological holdout.",
    )
    return parser


# =============================================================================
# 14. MAIN
# =============================================================================

def main() -> int:
    parser = build_parser()
    args = parser.parse_args()

    if args.cv_splits < 2 or args.inner_splits < 2 or args.cv_repeats < 1:
        parser.error("CV splits must be >=2 and repeats must be >=1.")
    if not 0 < args.max_normal_fpr < 1:
        parser.error("--max-normal-fpr must be in (0, 1).")
    if not 0 < args.time_test_fraction < 0.5:
        parser.error("--time-test-fraction must be in (0, 0.5).")

    args.output_dir.mkdir(parents=True, exist_ok=True)

    features_path = resolve_input_file(
        args.input_dir,
        args.features_file,
        "all_events_event_level_features.csv",
        "all_events_event_level_features*.csv",
    )
    raw_path = resolve_input_file(
        args.input_dir,
        args.raw_segments_file,
        "all_events_detected_segments_raw.csv",
        "all_events_detected_segments_raw*.csv",
    )
    timeline_path = resolve_input_file(
        args.input_dir,
        args.timeline_segments_file,
        "all_events_detected_segments.csv",
        "all_events_detected_segments(*).csv",
        required=False,
    )
    baseline_path = resolve_input_file(
        args.input_dir,
        args.baseline_decisions_file,
        "all_events_event_level_decisions.csv",
        "all_events_event_level_decisions*.csv",
        required=False,
    )

    print(f"[INPUT] Features: {features_path}")
    print(f"[INPUT] Raw segments: {raw_path}")
    print(f"[INPUT] Timeline: {timeline_path}")
    print(f"[INPUT] Baseline decisions: {baseline_path}")

    feature_table = load_feature_table(features_path)
    raw_segments = load_segment_table(raw_path)
    timeline = load_timeline_table(timeline_path)

    X, y, metadata, excluded_structural = create_model_dataset(
        feature_table=feature_table,
        raw_segments=raw_segments,
        timeline=timeline,
    )

    print(
        f"[DATA] Events={len(X)}, features={X.shape[1]}, "
        f"normal={(y == 0).sum()}, anomaly={(y == 1).sum()}"
    )

    # Save the exact model matrix for audit and reproducibility.
    model_matrix = pd.concat([metadata.reset_index(drop=True), X.reset_index(drop=True)], axis=1)
    model_matrix["target_binary"] = y.to_numpy()
    model_matrix.to_csv(args.output_dir / "ml_event_feature_matrix.csv", index=False)

    specs = build_model_specs(args.random_state)
    fold_metrics, repeated_predictions, comparison = run_repeated_nested_cv(
        X=X,
        y=y,
        metadata=metadata,
        specs=specs,
        cv_splits=args.cv_splits,
        cv_repeats=args.cv_repeats,
        inner_splits=args.inner_splits,
        random_state=args.random_state,
        max_normal_fpr=args.max_normal_fpr,
    )

    aggregated_predictions = aggregate_repeated_predictions(repeated_predictions)
    selected_model_name = select_final_model_name(
        comparison,
        args.interpretability_tolerance,
    )
    selected_spec = next(spec for spec in specs if spec.name == selected_model_name)

    selected_predictions = aggregated_predictions.loc[
        aggregated_predictions["model"] == selected_model_name
    ].copy()
    selected_metrics = calculate_binary_metrics(
        selected_predictions["actual_binary"],
        selected_predictions["predicted_binary"],
        selected_predictions["mean_anomaly_probability"],
    )
    selected_metrics["selected_model"] = selected_model_name
    selected_metrics["evaluation_type"] = "aggregated_repeated_nested_cv"

    baseline_metrics = evaluate_rule_baseline(baseline_path)
    if baseline_metrics is not None:
        selected_metrics["rule_baseline"] = baseline_metrics

    fold_metrics.to_csv(args.output_dir / "ml_outer_fold_metrics.csv", index=False)
    repeated_predictions.to_csv(
        args.output_dir / "ml_repeated_cv_predictions.csv", index=False
    )
    comparison.to_csv(args.output_dir / "ml_model_comparison.csv", index=False)
    aggregated_predictions.to_csv(
        args.output_dir / "ml_event_predictions_all_models.csv", index=False
    )
    selected_predictions.to_csv(
        args.output_dir / "ml_event_predictions.csv", index=False
    )
    write_json(
        args.output_dir / "ml_selected_model_metrics.json",
        selected_metrics,
    )

    selected_cm = confusion_matrix(
        selected_predictions["actual_binary"],
        selected_predictions["predicted_binary"],
        labels=[0, 1],
    )
    pd.DataFrame(
        selected_cm,
        index=["actual_normal", "actual_anomaly"],
        columns=["predicted_normal", "predicted_anomaly"],
    ).to_csv(args.output_dir / "ml_selected_model_confusion_matrix.csv")

    # Chronological holdout using only earlier events for training.
    time_predictions, time_metrics = run_time_holdout(
        spec=selected_spec,
        X=X,
        y=y,
        metadata=metadata,
        test_fraction=args.time_test_fraction,
        inner_splits=args.inner_splits,
        random_state=args.random_state + 999,
        max_normal_fpr=args.max_normal_fpr,
    )
    time_predictions.to_csv(
        args.output_dir / "ml_time_holdout_predictions.csv", index=False
    )
    write_json(args.output_dir / "ml_time_holdout_metrics.json", time_metrics)

    # Final model fitted on all available labelled events.
    final_estimator, final_params, final_threshold_result, training_probabilities = (
        train_final_model(
            selected_spec=selected_spec,
            X=X,
            y=y,
            inner_splits=args.inner_splits,
            random_state=args.random_state + 2026,
            max_normal_fpr=args.max_normal_fpr,
        )
    )

    final_predictions = (training_probabilities >= final_threshold_result.threshold).astype(int)
    training_prediction_df = metadata.copy()
    training_prediction_df["actual_binary"] = y.to_numpy()
    training_prediction_df["anomaly_probability"] = training_probabilities
    training_prediction_df["threshold"] = final_threshold_result.threshold
    training_prediction_df["predicted_binary"] = final_predictions
    training_prediction_df["predicted_label"] = training_prediction_df["predicted_binary"].map(LABEL_MAP)
    training_prediction_df["prediction_correct"] = (
        training_prediction_df["actual_binary"]
        == training_prediction_df["predicted_binary"]
    )
    training_prediction_df.to_csv(
        args.output_dir / "final_model_training_predictions.csv", index=False
    )

    importance = extract_feature_importance(final_estimator, list(X.columns))
    importance.to_csv(args.output_dir / "ml_feature_importance.csv", index=False)

    explanations = build_event_explanations(
        estimator=final_estimator,
        X=X,
        metadata=metadata,
        probabilities=training_probabilities,
        threshold=final_threshold_result.threshold,
        importance=importance,
    )
    explanations.to_csv(args.output_dir / "ml_event_explanations.csv", index=False)

    model_bundle = {
        "model_name": selected_model_name,
        "estimator": final_estimator,
        "threshold": final_threshold_result.threshold,
        "feature_columns": list(X.columns),
        "target_map": TARGET_MAP,
        "best_params": final_params,
        "threshold_selection": final_threshold_result.__dict__,
        "training_event_count": int(len(X)),
        "training_class_counts": {
            "normal": int((y == 0).sum()),
            "anomaly": int((y == 1).sum()),
        },
    }
    joblib.dump(model_bundle, args.output_dir / "event_level_model.joblib")

    save_plots(comparison, selected_predictions, args.output_dir)

    manifest = {
        "features_file": features_path,
        "raw_segments_file": raw_path,
        "timeline_segments_file": timeline_path,
        "baseline_decisions_file": baseline_path,
        "output_dir": args.output_dir,
        "event_count": len(X),
        "feature_count": X.shape[1],
        "feature_columns": list(X.columns),
        "excluded_empty_or_constant_columns": excluded_structural,
        "selected_model": selected_model_name,
        "final_best_params": final_params,
        "final_threshold": final_threshold_result.__dict__,
        "cv_splits": args.cv_splits,
        "cv_repeats": args.cv_repeats,
        "inner_splits": args.inner_splits,
        "max_normal_fpr": args.max_normal_fpr,
        "interpretability_tolerance": args.interpretability_tolerance,
        "time_test_fraction": args.time_test_fraction,
        "random_state": args.random_state,
    }
    write_json(args.output_dir / "training_manifest.json", manifest)

    print("\n[DONE] Event-level ML training completed.")
    print(f"[SELECTED MODEL] {selected_model_name}")
    print(f"[FINAL THRESHOLD] {final_threshold_result.threshold:.2f}")
    print(
        "[AGGREGATED REPEATED-CV] "
        f"balanced_accuracy={selected_metrics['balanced_accuracy']:.3f}, "
        f"F1={selected_metrics['f1_anomaly']:.3f}, "
        f"recall={selected_metrics['recall_anomaly']:.3f}, "
        f"specificity={selected_metrics['specificity_normal']:.3f}, "
        f"normal_FPR={selected_metrics['normal_false_positive_rate']:.3f}"
    )
    print(f"[OUTPUT] {args.output_dir}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
